project_name: hostlookuper
version: 2
release:
  github:
    owner: postfinance
    name: hostlookuper
builds:
  - id: hostlookuper
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./
    binary: hostlookuper
    env:
      - CGO_ENABLED=0
archives:
  - id: bindelivery
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}-{{ .Version }}"
    formats:
      - binary
checksum:
  name_template: checksums.txt
dockers_v2:
  - images:
      - postfinance/hostlookuper
      - ghcr.io/postfinance/hostlookuper
    tags:
      - "{{ .Version }}"
      - latest
    dockerfile: packaging/docker/Dockerfile
