project_name: hostlookuper
version: 2
release:
  github:
    owner: postfinance
    name: hostlookuper
builds:
  - id: hostlookuper
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./
    binary: hostlookuper
    env:
      - CGO_ENABLED=0
archives:
  - id: bindelivery
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}-{{ .Version }}"
    formats:
      - binary
checksum:
  name_template: checksums.txt
dockers:
  - image_templates:
      - "postfinance/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: packaging/docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .ShortCommit }}
      - --label=org.opencontainers.image.url=https://github.com/postfinance/hostlookuper
      - --label=org.opencontainers.image.vendor=PostFinance AG
      - --label=org.opencontainers.image.version={{ .Version }}
      - --pull
  - image_templates:
      - "postfinance/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: packaging/docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .ShortCommit }}
      - --label=org.opencontainers.image.url=https://github.com/postfinance/hostlookuper
      - --label=org.opencontainers.image.vendor=PostFinance AG
      - --label=org.opencontainers.image.version={{ .Version }}
      - --pull
docker_manifests:
  - name_template: postfinance/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - postfinance/{{ .ProjectName }}:{{ .Version }}-amd64
      - postfinance/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: postfinance/{{ .ProjectName }}:latest
    image_templates:
      - postfinance/{{ .ProjectName }}:{{ .Version }}-amd64
      - postfinance/{{ .ProjectName }}:{{ .Version }}-arm64v8
