apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostlookuper
spec:
  selector:
    matchLabels:
      app: hostlookuper
  template:
    metadata:
      labels:
        app: hostlookuper
    spec:
      containers:
      - name: hostlookuper
        image: postfinance/hostlookuper:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: HOSTLOOKUPER_INTERVAL
            value: 5s
          - name: HOSTLOOKUPER_DNS_SERVERS
            value: "udp://1.1.1.1:53"
          - name: HOSTLOOKUPER_HOSTS
            value: "google.ch,postfinance.ch,ch.ch"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: hostlookuper
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: hostlookuper
  ports:
  - port: 9090
    targetPort: 9090
