{
 "title": "Hostlookuper",
 "description": "Data starting from 15.01.2021",
 "tags": [
  "dns",
  "ITPost"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(hostlookuper_dns_lookup_total, dns_server)"
    }
   },
   {
    "name": "dns_server",
    "label": "DNS Server",
    "query": {
     "query": "label_values(hostlookuper_dns_lookup_total, dns_server)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(hostlookuper_dns_lookup_total{dns_server=~\"$protocol://$dns_server\"}, host)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hostlookuper_dns_lookup_total{}, instance)"
    }
   },
   { "name": "quantile", "label": "Quantile", "query": "0.99,0.95,0.90,0.50" }
  ]
 },
 "panels": [
  {
   "title": "Errors per DNS server",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hostlookuper_dns_errors_total{host=~\"$host\",dns_server=~\"$protocol://$dns_server\", instance=~\"$instance\"}[$__range])) by (dns_server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed lookups for $host host",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hostlookuper_dns_errors_total{dns_server=~\"$protocol://$dns_server\", instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error increase over last 15m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(hostlookuper_dns_errors_total{host=~\"$host\",dns_server=~\"$protocol://$dns_server\", instance=~\"$instance\"}[15m])) by (dns_server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RCODE repartition",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hostlookuper_dns_lookup_total{host=~\"$host\",dns_server=~\"$protocol://$dns_server\", instance=~\"$instance\", rcode!=\"\"}[$__range])) by (rcode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "buckets_limit(20,\n    prometheus_buckets(\n            sum(rate(\n                hostlookuper_dns_lookup_duration_seconds_bucket{dns_server=~\"$protocol://$dns_server\", instance=~\"$instance\"}[15m]\n            )) by (vmrange)\n            )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Lookup Error Rate",
   "type": "timeseries",
   "description": "Rate of lookup errors, aggregated over 1 minute.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hostlookuper_dns_errors_total{host=~\"$host\",dns_server=~\"$protocol://$dns_server\", instance=~\"$instance\"}[1m])) by (dns_server)",
     "legendFormat": "{{dns_server}}"
    }
   ]
  },
  {
   "title": "Lookup Rate",
   "type": "timeseries",
   "description": "Rate of performed lookups per second, aggregated over 1 minute.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hostlookuper_dns_lookup_total{host=~\"$host\",dns_server=~\"$protocol://$dns_server\", instance=~\"$instance\"}[1m]))  by (dns_server)",
     "legendFormat": "{{dns_server}}"
    }
   ]
  },
  {
   "title": "Lookup Duration ($quantile)",
   "type": "timeseries",
   "description": "Quantile of the time lookups took, aggregated over 1 minute.\n\nTimeout for lookups is 5s!",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(hostlookuper_dns_lookup_duration_seconds_bucket{instance=~\"$instance\", dns_server=~\"$protocol://$dns_server\"}[1m])) by (vmrange, host, dns_server))",
     "legendFormat": "{{host}},{{dns_server}}"
    }
   ]
  },
  {
   "title": "Lookup Duration Average",
   "type": "timeseries",
   "description": "Average duration a lookup took per host.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(hostlookuper_dns_lookup_duration_seconds_bucket{instance=~\"$instance\", dns_server=~\"$protocol://$dns_server\"}[1m])) by (vmrange, dns_server))",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}